# Generated by Django 4.2.5 on 2024-02-14 21:01

from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "employee_id",
                    models.CharField(
                        default=task.models.generate_employee_id,
                        max_length=7,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("date_of_joining", models.DateField()),
                ("last_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.employee"
                    ),
                ),
            ],
        ),
    ]
